on: [push, pull_request]
name: R-CMD-check
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - run: |
          Rscript -e 'options(repos = c(CRAN="https://cloud.r-project.org"));
                      install.packages(c("remotes","devtools"))'
      - run: Rscript -e 'remotes::install_deps(dependencies = TRUE)'
      - run: R CMD check --no-manual --as-cran .
